### PR TITLE
renamed `standardLibrary` XML attribute to `standard_library` 

### PR DESCRIPTION
**Pull request by apdavison**
to match spec (cf https://github.com/INCF/NineMLCatalog/commit/e28a06d8f6da9c88073143ac30c2c41aa81822b4)

### CODE REVIEW

**Comment by tclose** [comment]
Can you update the xml in the "_old" examples folder which is causing test_network to fail? (I think test_network has been updated in my latest branch to not use this folder but for the time being it would be easier just to change it)

**Comment by apdavison** [comment]
@tclose I forgot this hadn't been merged, and have added another commit. Please can you check it's ok.

**Comment by NineML-Committee** [comment]
Yep looks good.

**Comment by tclose** [comment]
Sorry, not sure why that came up as the committee.

**Pull request merged**
